# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: Default

variables:
  solution: '**/App/*.sln'
  buildPlatform: 'Any Cpu'
  buildConfiguration: 'Release'



steps:
# Restore buld and test
  - task: DotNetCoreCLI@2
    displayName: Restore Project Dependencies
    inputs:
      command: 'restore'
      projects: '$(solution)'
      feedsToUse: 'select'
  
  - task: DotNetCoreCLI@2
    displayName: Build Projects
    inputs:
      command: 'build'
      projects: '$(solution)'
      
  - task: DotNetCoreCLI@2
    displayName: Running Tests
    inputs:
      command: 'test'
      projects: '$(solution)'
  
  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: 'publish'
      publishWebProjects: false
      zipAfterPublish: true
      projects: '$(solution)/$(soulution_main)'

  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'Azure subscription 1(b9ea6d04-6500-4af6-adfa-84ac2185ff53)'
      appType: 'webAppLinux'
      WebAppName: 'watches-n-such'
      packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
      RuntimeStack: 'DOTNETCORE|5.0'



# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'
