# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: Default

variables:
  solution: '**/App/*.sln'
  buildPlatform: 'Any Cpu'
  buildConfiguration: 'Release'
  solution_main: 'WebUI'
  solution_root: 'App'

steps:

  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'Sonar-Cloud-Service'
      organization: '210503-reston-net'
      scannerMode: 'MSBuild'
      projectKey: '210503-Reston-NET_Ruffner-Garrett-P1'
      projectName: 'Ruffner-Garrett-P1'

# Restore, Build, Test, Deploy
  - task: DotNetCoreCLI@2
    displayName: Restore Project Dependencies
    inputs:
      command: 'restore'
      projects: '$(solution)'
      feedsToUse: 'select'
  
  - task: DotNetCoreCLI@2
    displayName: Build Projects
    inputs:
      command: 'build'
      projects: '$(solution)'
      
  # - task: DotNetCoreCLI@2
  #   displayName: 'Install ReportGenerator'
  #   inputs:
  #     command: custom
  #     custom: tool
  #     arguments: 'install --global dotnet-reportgenerator-globaltool'

  - task: DotNetCoreCLI@2
    displayName: 'Run unit tests - $(buildConfiguration)'
    inputs:
      command: 'test'
      arguments: '--configuration $(buildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura'

      publishTestResults: true
      projects: '$(solution)'


# /p:CoverletOutput=$(Build.SourcesDirectory)/TestResults/Coverage/'
    
  # - script: |
  #     export PATH="$PATH:$HOME/.dotnet/tools"
  #   displayName: 'Setup for tools'
  # /dotnetglobaltools/reportgenerator -reports:$(Build.SourcesDirectory)/TestResults/Coverage/* -targetdir:$(Build.SourcesDirectory)/CodeCoverage -reporttypes:Xml
  - script: |
      /dotnetglobaltools/reportgenerator -reports:**/coverage.cobertura.xml -targetdir:Report -reporttypes:HtmlInline_AzurePipelines;Cobertura
    displayName: 'Create code coverage report'

  - task: PublishCodeCoverageResults@1
    displayName: 'Publish code coverage report'
    inputs:
      # codeCoverageTool: 'cobertura'
      # summaryFileLocation: '$(Build.SourcesDirectory)/CodeCoverage/*'
      # additionalCodeCoverageFiles: 
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(Build.SourcesDirectory)/CodeCoverage/Cobertura.xml'
      reportDirectory: '$(Build.SourcesDirectory)/CodeCoverage'

  # - task: DotNetCoreCLI@2
  #   displayName: Running Tests
  #   inputs:
  #     command: 'test'
  #     projects: '$(solution)'
  #     arguments: --configuration $(buildConfiguration) --collect "Code Coverage"
  # - task: PublishCodeCoverageResults@1
  #   displayName: Publish Code Coverage
  #   inputs:
  #     codeCoverageTool: 'Cobertura'
  #     summaryFileLocation: '**/*.coverage'

  - task: SonarCloudAnalyze@1
    displayName: Run Code Analysis
  - task: SonarCloudPublish@1
    displayName: Publish Code Analysis
  
  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: 'publish'
      publishWebProjects: false
      zipAfterPublish: true
      projects: '**/App/WebUI/*.csproj'

  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'Azure subscription 1(b9ea6d04-6500-4af6-adfa-84ac2185ff53)'
      appType: 'webAppLinux'
      WebAppName: 'watches-n-such'
      packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
      RuntimeStack: 'DOTNETCORE|5.0'

